server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CloudVendor_Db
    username: root
    password: root
#JPA settings
  jpa.hibernate.ddl_auto: update
  jpa.properties.hibernate.format_sql : true
  jpa.properties.hibernate.show_sql: true
  jpa.hibernate.naming.physical-strategy : org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
